accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("<str:username>/", views.UserProfileView.as_view(), name="profile"),
    path("<str:username>/follow/", views.FollowView.as_view(), name="follow"),
    path("<str:username>/unfollow/", views.UnFollowView.as_view(), name="unfollow"),
    path(
        "<str:username>/following_list/",
        views.FollowingListView.as_view(),
        name="following_list",
    ),
    path(
        "<str:username>/follower_list/",
        views.FollowerListView.as_view(),
        name="follower_list",
    ),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("tweets/", include("tweets.urls")),
    path("", include("welcome.urls")),
]

tweets/urls.py
from django.urls import path

from . import views

app_name = "tweets"
urlpatterns = [
    path("home/", views.HomeView.as_view(), name="home"),
    path("create/", views.TweetCreateView.as_view(), name="create"),
    path("<int:pk>/", views.TweetDetailView.as_view(), name="detail"),
    path("<int:pk>/delete/", views.TweetDeleteView.as_view(), name="delete"),
    path("<int:pk>/like/", views.LikeView.as_view(), name="like"),
    path("<int:pk>/unlike/", views.UnlikeView.as_view(), name="unlike"),
]

accounts/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _


class CustomUser(AbstractUser):
    email = models.EmailField(_("email address"))
    following = models.ManyToManyField(
        "self",
        related_name="follow_by",
        through="FriendShip",
        symmetrical=False,
    )


class FriendShip(models.Model):
    follower = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="follower",
        on_delete=models.CASCADE,
    )
    followee = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="followee",
        on_delete=models.CASCADE,
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["follower", "followee"],
                name="unique_friendship",
            )
        ]

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

CustomUser = get_user_model()


class SignupForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ["username", "email", "password1", "password2"]


class LoginForm(AuthenticationForm):
    class Meta:
        model = CustomUser
        fields = ["username", "password"]

accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, get_user_model, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.http import HttpResponseBadRequest
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, RedirectView, TemplateView

from tweets.models import Like, Tweet

from .forms import LoginForm, SignupForm
from .models import FriendShip

CustomUser = get_user_model()


class WelcomeView(CreateView):
    pass


class SignUpView(CreateView):
    model = CustomUser
    template_name = "accounts/signup.html"
    form_class = SignupForm
    success_url = "/tweets/home/"

    def form_valid(self, form):
        response = super().form_valid(form)
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password1")
        user = authenticate(username=username, password=password)
        login(self.request, user)
        return response


class LoginView(LoginView):
    template_name = "accounts/login.html"
    form_class = LoginForm


class LogoutView(LogoutView):
    pass


class UserProfileView(LoginRequiredMixin, ListView):
    template_name = "accounts/profile.html"
    model = Tweet
    context_object_name = "tweets_list"

    def get_queryset(self):
        return (
            Tweet.objects.select_related("user")
            .prefetch_related("liked_tweet")
            .filter(user__username=self.kwargs.get("username"))
            .order_by("-created_at")
        )

    def get_context_data(self, **kwargs):
        user = get_object_or_404(CustomUser, username=self.kwargs["username"])
        context = super().get_context_data(**kwargs)
        context["username"] = user.username
        context["is_following"] = self.request.user.following.filter(username=user.username).exists()
        context["following_count"] = FriendShip.objects.filter(follower=user).count()
        context["follower_count"] = FriendShip.objects.filter(followee=user).count()
        context["liked_list"] = (
            Like.objects.select_related("tweet").filter(user=self.request.user).values_list("tweet", flat=True)
        )
        return context


class FollowView(LoginRequiredMixin, RedirectView):
    url = reverse_lazy("tweets:home")

    def post(self, request, *args, **kwargs):
        target_user = get_object_or_404(CustomUser, username=self.kwargs["username"])
        if target_user == self.request.user:
            messages.add_message(request, messages.ERROR, "自分自身をフォローすることはできません。")
            return HttpResponseBadRequest("you cannnot follow yourself.")
        elif self.request.user.following.filter(username=target_user.username).exists():
            messages.add_message(request, messages.INFO, "既にフォローしています。")
        else:
            self.request.user.following.add(target_user)
            messages.add_message(request, messages.SUCCESS, "フォローしました。")
        return super().post(request, *args, **kwargs)


class UnFollowView(LoginRequiredMixin, RedirectView):
    url = reverse_lazy("tweets:home")

    def post(self, request, *args, **kwargs):
        target_user = get_object_or_404(CustomUser, username=self.kwargs["username"])
        if target_user == self.request.user:
            messages.add_message(request, messages.ERROR, "自分自身をフォロー解除することはできません。")
            return HttpResponseBadRequest("you cannot unfollow yourself.")
        elif self.request.user.following.filter(username=target_user.username).exists():
            self.request.user.following.remove(target_user)
            messages.add_message(request, messages.SUCCESS, "フォロー解除しました。")
        else:
            messages.add_message(request, messages.INFO, "このユーザーをフォローしていません。")
        return super().post(request, *args, **kwargs)


class FollowingListView(LoginRequiredMixin, TemplateView):
    template_name = "accounts/following_list.html"

    def get_context_data(self, **kwargs):
        target_user = get_object_or_404(
            CustomUser,
            username=self.kwargs.get("username"),
        )
        context = super().get_context_data(**kwargs)
        context["following_list"] = target_user.follower.order_by("-created_at")
        return context


class FollowerListView(LoginRequiredMixin, TemplateView):
    template_name = "accounts/follower_list.html"

    def get_context_data(self, **kwargs):
        target_user = get_object_or_404(
            CustomUser,
            username=self.kwargs.get("username"),
        )
        context = super().get_context_data(**kwargs)
        context["follower_list"] = target_user.followee.order_by("-created_at")
        return context

templates/accounts/follower_list.html
{% extends 'base.html' %}

{% block title %}FollowerList{% endblock %}

{% block content %}
<h1>{{ username }}のフォロワーリスト</h1>
<div>
    {% for target_user in follower_list %}
    <p>
        <a href="{% url 'accounts:profile' target_user.follower.username %}">{{target_user.follower.username}}</a>
    </p>
    {% endfor %}
</div>

{% endblock %}

templates/accounts/following_list.html
{% extends 'base.html' %}

{% block title %}FollowingList{% endblock %}

{% block content %}
<h1>{{ username }}のフォローリスト</h1>
<div>
    {% for target_user in following_list %}
    <p>
        <a href="{% url 'accounts:profile' target_user.followee.username %}">{{target_user.followee.username}}</a>
    </p>
    {% endfor %}
</div>

{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}loginForm{% endblock %}

{% block content %}
<h1>ログイン</h1>
<form action="{% url 'accounts:login' %}" method="post">
    {{ form.as_p }}
    {% csrf_token %}

    <p><input type="submit" value="ログイン"></p>
</form>
{% endblock %}

templates/accounts/profile.html
{% extends 'base.html' %}
{% block title %}Profile{% endblock %}

{% block content %}

<h1>{{ username }}のプロフィール</h1>

{% if username != request.user.username %}
<form method="POST">
    {% csrf_token %}
    {% if is_following %}
    <button type="submit" formaction="{% url 'accounts:unfollow' username %}">フォロー解除</button>
    {% else %}
    <button type="submit" formaction="{% url 'accounts:follow' username %}">フォロー</button>
    {% endif %}
</form>
{% endif %}

<div>
    <br>
    <a href="{% url 'accounts:following_list' username %}">フォロー数：{{ following_count }}</a>
    <br>
    <a href="{% url 'accounts:follower_list' username %}">フォロワー数：{{ follower_count }}</a>
</div>

<br>
<h3>過去のツイート一覧</h3>
{% include 'tweets/like_script.html' %}
{% for tweet in tweets_list %}
<div>
    <p>{{tweet.user.username}}</p>
    <p>{{tweet.created_at}}</p>
    <p>{{tweet.content}}
        <a><a href="{% url 'tweets:detail' tweet.pk %}">詳細</a>
    </p>
    {% include "tweets/like.html" %}
</div>
{% endfor %}

{% endblock %}

templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %}signupForm{% endblock %}

{% block content %}
<h1>ユーザー登録</h1>
<form action="{% url 'accounts:signup' %}" method="post">
    {{ form.as_p }}
    {% csrf_token %}

    <p><input type="submit" value="登録"></p>
</form>

{%endblock%}