accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("<str:username>/", views.UserProfileView.as_view(), name="profile"),
    path("<str:username>/follow/", views.FollowView.as_view(), name="follow"),
    path("<str:username>/unfollow/", views.UnFollowView.as_view(), name="unfollow"),
    path(
        "<str:username>/following_list/",
        views.FollowingListView.as_view(),
        name="following_list",
    ),
    path(
        "<str:username>/follower_list/",
        views.FollowerListView.as_view(),
        name="follower_list",
    ),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("tweets/", include("tweets.urls")),
    path("", include("welcome.urls")),
]

tweets/urls.py
from django.urls import path

from . import views

app_name = "tweets"
urlpatterns = [
    path("home/", views.HomeView.as_view(), name="home"),
    path("create/", views.TweetCreateView.as_view(), name="create"),
    path("<int:pk>/", views.TweetDetailView.as_view(), name="detail"),
    path("<int:pk>/delete/", views.TweetDeleteView.as_view(), name="delete"),
    path("<int:pk>/like/", views.LikeView.as_view(), name="like"),
    path("<int:pk>/unlike/", views.UnlikeView.as_view(), name="unlike"),
]

tweets/models.py
from django.conf import settings
from django.db import models


class Tweet(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField(verbose_name="内容", max_length=140)
    created_at = models.DateTimeField(verbose_name="投稿日", auto_now_add=True)


class Like(models.Model):
    tweet = models.ForeignKey(Tweet, on_delete=models.CASCADE, related_name="liked_tweet")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="like_user")

    class Meta:
        constraints = [models.UniqueConstraint(fields=["tweet", "user"], name="unique_like")]

tweets/forms.py
from django import forms
from django.forms import ModelForm

from .models import Tweet


class TweetForm(ModelForm):
    content = forms.CharField(
        max_length=140,
        widget=forms.Textarea(attrs={"rows": 5, "cols": 40, "placeholder": "いまなにしてる？"}),
    )

    class Meta:
        model = Tweet
        fields = ("content",)

tweets/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import CreateView, DeleteView, DetailView, ListView

from .forms import TweetForm
from .models import Like, Tweet


class HomeView(LoginRequiredMixin, ListView):
    model = Tweet
    template_name = "tweets/home.html"
    queryset = Tweet.objects.select_related("user").prefetch_related("liked_tweet")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["liked_list"] = (
            Like.objects.select_related("tweet").filter(user=self.request.user).values_list("tweet", flat=True)
        )
        return context


class TweetCreateView(LoginRequiredMixin, CreateView):
    template_name = "tweets/create.html"
    model = Tweet
    form_class = TweetForm
    success_url = reverse_lazy("tweets:home")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class TweetDetailView(LoginRequiredMixin, DetailView):
    template_name = "tweets/detail.html"
    model = Tweet
    queryset = Tweet.objects.select_related("user").prefetch_related("liked_tweet")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["liked_list"] = (
            Like.objects.select_related("tweet")
            .filter(tweet=self.object, user=self.request.user)
            .values_list("tweet", flat=True)
        )
        return context


class TweetDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    template_name = "tweets/delete.html"
    model = Tweet
    success_url = reverse_lazy("tweets:home")

    def test_func(self):
        return self.request.user == self.get_object().user


class LikeView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        tweet_id = self.kwargs["pk"]
        tweet = get_object_or_404(Tweet, pk=tweet_id)
        user = self.request.user
        Like.objects.get_or_create(tweet=tweet, user=user)
        is_liked = True
        like_url = reverse("tweets:like", kwargs={"pk": tweet_id})
        unlike_url = reverse("tweets:unlike", kwargs={"pk": tweet_id})
        like_count = tweet.liked_tweet.count()
        context = {
            "like_count": like_count,
            "tweet_id": tweet_id,
            "is_liked": is_liked,
            "like_url": like_url,
            "unlike_url": unlike_url,
        }
        return JsonResponse(context)


class UnlikeView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        tweet_id = self.kwargs["pk"]
        tweet = get_object_or_404(Tweet, pk=tweet_id)
        user = self.request.user
        Like.objects.filter(user=user, tweet=tweet).delete()  # 該当するLike.objectsが存在する場合のみdelete
        is_liked = False
        like_url = reverse("tweets:like", kwargs={"pk": tweet_id})
        unlike_url = reverse("tweets:unlike", kwargs={"pk": tweet_id})
        like_count = tweet.liked_tweet.count()
        context = {
            "like_count": like_count,
            "tweet_id": tweet_id,
            "is_liked": is_liked,
            "like_url": like_url,
            "unlike_url": unlike_url,
        }
        return JsonResponse(context)

templates/tweets/create.html
{% extends 'base.html' %}
{% block title %}tweet_create{% endblock %}
{% block content %}

<body>
    <h1>ツイート作成</h1>
    <p><a href="{% url 'accounts:logout' %}">ログアウト</a></p>
    <h2>ユーザー名：{{user.username}}</h2>
    <h2>
        <form method="post">
            {{ form.as_p}}
            {% csrf_token %}
            <button type="submit">投稿</button>
        </form>
    </h2>
</body>
{% endblock %}

templates/tweets/delete.html
{% extends 'base.html' %}
{% block title %}tweets_delete{% endblock %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <p>本当にこの投稿を削除してよろしいですか？</p>
    <p>{{ tweet.user.username }}</p>
    <p>{{ tweet.content }}</p>
    <p>{{ tweet.created_at }}</p>
    <button type="submit">削除</button>
</form>
{% endblock %}

templates/tweets/detail.html
{% extends 'base.html' %}
{% block title %}tweets_detail{% endblock %}
{% block content %}
<div>
    <a>{{tweet.user}}</a>
    <p>{{tweet.created_at}}</p>
    <p>{{tweet.content}}</p>

    {% if tweet.user == request.user %}
    <p>
        <a href="{% url 'tweets:delete' tweet.pk %}">削除</a>
    </p>
    {% endif %}
</div>

{% include "tweets/like.html" %}
{% include 'tweets/like_script.html' %}

{% endblock %}

templates/tweets/home.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block content %}

<body>
    {% include 'tweets/like_script.html' %}
    <h1>Home</h1>
    <h2>ユーザー名：{{user.username}}</h2>
    <p><a href="{% url 'tweets:create' %}">ツイートする！</a></p>

    <h2>投稿一覧</h2>
    {% for tweet in tweet_list %}
    <div>
        <a href="{% url 'accounts:profile' tweet.user.username %}">{{tweet.user.username}}</a>
        <p>{{tweet.created_at}}</p>
        <p>{{tweet.content}}
            <a><a href="{% url 'tweets:detail' tweet.pk %}">詳細</a>
        </p>
        {% include "tweets/like.html" %}

    </div>
    {% endfor %}
    </div>


</body>


{% endblock %}

templates/tweets/like.html
<!-- tweet.idへのいいねElementを取得 -->
{% if tweet.id in liked_list %}
<button id="tweet-{{tweet.id}}" onclick="changeLike(id)" data-url="{% url 'tweets:unlike' tweet.id %}">いいねを取り消す</button>
{% else %}
<button id="tweet-{{tweet.id}}" onclick="changeLike(id)" data-url="{% url 'tweets:like' tweet.id %}">いいね</button>
{% endif %}
<span class="count_{{tweet.id}}">{{tweet.liked_tweet.count}}</span>

templates/tweets/like_script.html
<script>
    const getCookie = (name) => {
        if (document.cookie && document.cookie !== '') {
            for (const cookie of document.cookie.split(';')) {
                const [key, value] = cookie.trim().split('=')
                if (key === name) {
                    return decodeURIComponent(value)
                }
            }
        }
    }
    const csrftoken = getCookie('csrftoken')

    const changeLike = async (id) => {
        const like_button = document.querySelector("#" + id)
        const url = like_button.dataset.url;
        const response = await fetch(url, {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "X-CSRFToken": csrftoken,
            }
        });
        const tweet_data = await response.json();
        changeStyle(tweet_data, like_button);
    }

    const changeStyle = (tweet_data, like_button) => {
        const like_count = document.querySelector(".count_" + tweet_data.tweet_id)
        if (tweet_data.is_liked) {
            unlike_url = tweet_data.unlike_url;
            like_button.setAttribute("data-url", unlike_url);
            like_button.innerHTML = "いいねを取り消す";
            like_count.textContent = tweet_data.like_count;
        } else {
            like_url = tweet_data.like_url;
            like_button.setAttribute("data-url", like_url);
            like_button.innerHTML = "いいね";
            like_count.textContent = tweet_data.like_count;
        }
    }
</script>

templates/tweets/tweet_create.html
{% extends 'base.html' %}
{% block title %}tweet_create{% endblock %}
{% block content %}

<body>
    <h1>ツイート作成</h1>
    <p><a href="{% url 'accounts:logout' %}">ログアウト</a></p>
    <h2>ユーザー名：{{user.username}}</h2>
</body>
{% endblock %}