accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("<str:username>/", views.UserProfileView.as_view(), name="profile"),
    path("<str:username>/follow/", views.FollowView.as_view(), name="follow"),
    path("<str:username>/unfollow/", views.UnFollowView.as_view(), name="unfollow"),
    path(
        "<str:username>/following_list/",
        views.FollowingListView.as_view(),
        name="following_list",
    ),
    path(
        "<str:username>/follower_list/",
        views.FollowerListView.as_view(),
        name="follower_list",
    ),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("tweets/", include("tweets.urls")),
    path("", include("welcome.urls")),
]

tweets/urls.py
from django.urls import path

from . import views

app_name = "tweets"
urlpatterns = [
    path("home/", views.HomeView.as_view(), name="home"),
    path("create/", views.TweetCreateView.as_view(), name="create"),
    path("<int:pk>/", views.TweetDetailView.as_view(), name="detail"),
    path("<int:pk>/delete/", views.TweetDeleteView.as_view(), name="delete"),
    path("<int:pk>/like/", views.LikeView.as_view(), name="like"),
    path("<int:pk>/unlike/", views.UnlikeView.as_view(), name="unlike"),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="ja">

<head>
    <link rel="stylesheet" href="style.css">
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <b>MENU</b>
    {% if request.user.is_authenticated %}
    <div id="sidebar">
        <ul>
            <li><a href="{% url 'tweets:home' %}">Home</a></li>
        </ul>
        <ul>
            <li><a href="{% url 'accounts:profile' user.username %}">Profile</a></li>
        </ul>
        <ul>
            <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
        </ul>
    </div>
    {% else %}
    <div id="sidebar">
        <ul>
            <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
        </ul>
        <ul>
            <li><a href="{% url 'accounts:login' %}">Login</a></li>
        </ul>
    </div>
    {% endif %}
    {% for message in messages %}
    <div {% if message.tags %}class="{{ message.tags }}" {% endif %}>
        通知：{{ message }}
    </div>
    {% endfor %}
    <div id="content">
        {% block content %}{% endblock %}
    </div>

</body>

</html>